sudo: required

language: bash

services:
  - docker

script:
  - chmod +x build.sh
  - ./build.sh

notifications:
  email:
    recipients:
      - i@i-meto.com
    on_success: always
    on_failure: always
